// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VendingMachine.ApplicationCore.DomModels;

#nullable disable

namespace VendingMachine.Migrations
{
    [DbContext(typeof(VendingMachineDbContext))]
    partial class VendingMachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Coca-Cola"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepsi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sprite"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fanta"
                        });
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Denomination")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Denomination = 1.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Denomination = 2.00m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            Denomination = 5.00m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = 4,
                            Denomination = 10.00m,
                            Quantity = 50
                        });
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Coca-Cola Classic",
                            Price = 80.00m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Coca-Cola Zero",
                            Price = 80.00m,
                            QuantityInStock = 40
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Pepsi",
                            Price = 75.00m,
                            QuantityInStock = 60
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "Pepsi Max",
                            Price = 75.00m,
                            QuantityInStock = 30
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Name = "Sprite",
                            Price = 70.00m,
                            QuantityInStock = 45
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            Name = "Sprite Zero",
                            Price = 70.00m,
                            QuantityInStock = 20
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 4,
                            Name = "Fanta Orange",
                            Price = 85.00m,
                            QuantityInStock = 50
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 4,
                            Name = "Fanta Pineapple",
                            Price = 85.00m,
                            QuantityInStock = 25
                        });
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.OrderItem", b =>
                {
                    b.HasOne("VendingMachine.ApplicationCore.DomModels.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VendingMachine.ApplicationCore.DomModels.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Product", b =>
                {
                    b.HasOne("VendingMachine.ApplicationCore.DomModels.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("VendingMachine.ApplicationCore.DomModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
